apiVersion: batch/v1
kind: CronJob
metadata: { name: cj-chroma-upsert }
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl:8.8.0
              env:
                - name: TOKEN
                  valueFrom: { secretKeyRef: { name: api-auth, key: API_BEARER_TOKEN } }
              command: ["sh","-lc"]
              args:
                - >
                  curl -sS -X POST
                  -H "Authorization: Bearer $TOKEN"
                  -H "Content-Type: application/json"
                  --data '{"collections":["portal_field_ja","portal_view_common_ja"],"limit":1000,"dry_run":false}'
                  http://portal-api.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local/chroma/upsert
