apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
  labels:
    app: chroma
spec:
  serviceName: chroma
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
        - name: chroma
          image: python:3.11-slim
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -euo pipefail
              chmod +x /bootstrap/entrypoint.sh || true
              exec /bootstrap/entrypoint.sh
          env:
            - name: PERSIST_DIRECTORY
              value: /chroma
          ports:
            - name: http
              containerPort: 8000
          # pip インストール時間を考慮して猶予を長めに
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /chroma
            - name: bootstrap
              mountPath: /bootstrap
      volumes:
        - name: bootstrap
          configMap:
            name: chroma-bootstrap
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
